sudo: true
language: perl
perl:
  - "blead"
  - "dev"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
matrix:
  allow_failures:
    - perl: blead
before_install:
  - sudo -H pip install docutils
  - sudo -H apt-get install asciidoc
  - eval $(curl https://travis-perl.github.io/init) --auto
